apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verrazzano-test-role
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - pods/status
      - ingresses
      - services
      - secrets
    verbs:
      - get
      - list
      - watch